### ISSUE TITLE
Warning Undefined array key "ETAT_PBX" sur la réponse de Paybox suite à un paiement

### ISSUE THREAD

**Issue by cy-altern** [nursit/bank#101]
En PHP 8 suite à un paiement "basique" avec le prestataire Paybox (mais avec affichage du retour avant sa redirection pour tester le pipeline `bank_description_transaction`),  j'obtiens :
```
Warning: Undefined array key "ETAT_PBX" in ...plugins/bank/presta/paybox/call/response.php on line 44
```
ce qui correspond à `if ($response['ETAT_PBX']==='PBX_RECONDUCTION_ABT'){ `

Dans ce cas d'usage de transaction basique, un `var_dump($response)` donne :
```
array (size=9)
  'montant' => string '6800' (length=4)
  'id_transaction' => string '6450' (length=4)
  'auth' => string 'XXXXXX' (length=6)
  'trans' => string '37086378' (length=8)
  'abo' => string '0' (length=1)
  'erreur' => string '00000' (length=5)
  'carte' => string 'CB' (length=2)
  'BIN6' => string '111122' (length=6)
  'valid' => string '2402' (length=4)
```
Alors vu que dans la suite de ce fichier il y a 4 fois ce même test sur `$response['ETAT_PBX']`, il semblerait utile de "neutraliser" cette clé si elle est manquante en la déclarant à vide avant son premier appel...

**Comment by Cerdic** [comment]
Merci pour le retour, c'est corrigé (j'ai préféré doubler un test sur empty et refactorer un peu pour éviter de modifier la `$response` car c'est normalement ce qu'on reçoit de Paybox et ça m'embête un peu de la triturer car ça peut parasiter le debug en cas de soucis
