### ISSUE TITLE
Presta Stripe - Nouvelle API (15/11/2022)

### ISSUE THREAD

**Issue by JuLBLoBuL** [nursit/bank#105]
Il existe une nouvelle API Stripe  (15/11/2022), incompatible avec la version actuelle (et précédente) de Bank.
Les nouveaux utilisateurs de Stripe sont forcés d'utiliser cette nouvelle version, ils peuvent donc pas utiliser Bank.
Voici le genre d'erreur généré : 
L210: You cannot use `line_items.amount`, `line_items.currency`, `line_items.name`, `line_items.description`, or `line_items.images` in this API version. Please use `line_items.price` or `line_items.price_data`. 

Plus d'info :
https://stripe.com/docs/payments/checkout/migrating-prices

**Comment by Cerdic** [comment]
Ah ben zutalors !

**Comment by JuLBLoBuL** [comment]
Je veux bien m'en occuper, je crois que c'est à ma portée ;)

**Comment by Cerdic** [comment]
Je pense que tu utilises une ancienne version du plugin, je t'invite à commencer par mettre à jour. Car ici https://support.stripe.com/questions/prices-api-and-existing-checkout-integrations je lis "You do not have to make any changes to your Stripe Checkout integration"

Si tu as toujours le problème, un rapport d'erreur plus circonstancié serait approprié - pas "le genre d'erreur" mais l'erreur exact que tu obtiens dans les logs avec fichier et ligne concernée...

En tout cas on a rien L210 qui correspond à ton erreur et comme tu peux le voir https://github.com/nursit/bank/blob/master/presta/stripe/call/request.php#L210 on utilise déjà `price_data`...

**Comment by JuLBLoBuL** [comment]
J'utilise effectivement une version custom, les lignes ne correspondent donc pas forcement.
Dans la dernière version, il faut plutôt regarder à partir de la ligne 147.
https://github.com/nursit/bank/blob/master/presta/stripe/call/request.php#L147
**amount** devrait être **price** par exemple comme expliqué ici :
https://stripe.com/docs/payments/checkout/migrating-prices#server-side-code-for-inline-items

**Comment by Cerdic** [comment]
Non désolé, mais ton code ne correspond manifestement pas et dans l'exemple que tu donnes au dessus `amount` est utilisé dans un `price_data` https://github.com/nursit/bank/blob/master/presta/stripe/call/request.php#L224

Je ferme ici parce qu'on ne peut pas faire de la maintenance sur des forks ^^

Si tu reproduis avec une version non forkée et à jour du plugin tu peux ré-ouvrir en indiquant les détails
