### ISSUE TITLE
Paybox : autoresponse configuration

### ISSUE THREAD

**Issue by w4rell** [nursit/bank#110]
Bonjour,

J’ai pu intégrer paybox dans un formulaire pour effectuer des donations, seulement la gestion de la réponse semble HS, le paiement se fait bien, mais le back-office n’est jamais informée du statut du paiement.

Paybox m’a envoyé le mail suivant (je précise que j'ai bien configuré l'url du site dans l'espace du coté Paybox, j'ai juste remplacé les URL par telsite) :

    WARNING: Impossible de joindre https://telsite.org/bank.api/paybox-4316/autoresponse/ https://telsite.org/bank.api/paybox-4316/autoresponse/ pour le paiement “montant=100&id_transaction=12&auth=XXXXXX&trans=XXXXXXXX&abo=0&erreur=00000&carte=CB&BIN6=------&valid=2504&sign=xl4vT6kqOp6C3cq6cidscNK8P1MCLPqrVpS8FzSAzJYSr7toQKUhhvq8qdOVXhSFVof06xz4vaXGw921kvc3Xc8aTyYcY95YbpHUWD004ed2KVI2JWYxJgimPTpe6wBJaQtbsiP%2FvDgtoCJ4AVj%2Bo27D957OdpMOe91Sfw%3D”
    Erreur : code HTTP: 404

Est-ce que ca peut avoir un lien avec la gestion des URL dans SPIP ?

Merci beaucoup pour votre aide.

**Comment by Cerdic** [comment]
Je suppose qu'il vous manque cette RewriteRule dans votre fichier htaccess
https://git.spip.net/spip/spip/src/branch/master/htaccess.txt#L87

Ce qui est étonnant c'est que normalement le plugin propose une URL en bank.api uniquement si elle est bien présente dans le htaccess. Ou alors votre htaccess n'est pas actif ou bien vous n'utilisez pas apache et alors il faut une directive équivalente...

**Comment by w4rell** [comment]
Merci beaucoup, c'était bien le .htaccess, dans mon apache2.conf, avec la conf auto de certbot, j'ai rajouté ce code en dessous afin de prendre en compte le fichier.

```
<Directory /var/www/html/>
  AllowOverride all
  Require all granted
</Directory>
```
