### ISSUE TITLE
Paybox : remplir le champ Adress1 de la variable PBX_BILLING

### ISSUE THREAD

**Issue by cy-altern** [nursit/bank#118]
pour être conforme 3DSv2, la doc de Up2Pay (l'implémentation Crédit Agricole de Paybox) sur https://www.ca-moncommerce.com/espace-client-mon-commerce/up2pay-e-transactions/ma-documentation/manuel-dintegration-focus-3ds-v2/principes-generaux/#integration-3dsv2-developpeur-webmaster donne comme obligatoires pour la variable `PBX_BILLING` tous les champs listés sauf `Adress2`
 
Ayant reçu une injonction de mise en conformité d'ici le 30/09/2023 il semblerait qu'il ne soit pas possible de laisser vide le contenu de ces champs comme c'est le cas pour `Adress1` (cf https://github.com/nursit/bank/blob/1a3a6871af6d163df92aa6b0b3c419f807212a73/presta/paybox/call/request.php#L105)

**Comment by Cerdic** [comment]
Alors : oui la variable est obligatoire, c'était aussi indiqué dans la doc de Paybox
https://github.com/nursit/bank/issues/99#issuecomment-1286894258

MAIS, comme ces specs sont mal foutues ça ne veut pas dire qu'elles doivent être remplies

Comme par ailleurs les banques en profitent pour aspirer un max de données, j'ai considéré que filer le CP et la ville c'était déjà bien suffisant, on a pas besoin de leur donner notre carnet d'adresse de clients, dont ne sait pas ce qu'elles vont faire...

Donc ça me plait pas bien de fournir l'adresse ici, mais je vois que j'ai aussi été obligé de le faire sur CMCIC et Payzen.

C'est un peu paradoxal, mais in fine celui qui aspire le moins de données c'est Stripe...

**Comment by cy-altern** [comment]
on est d'accord sur le fait de refiler le moins de données possibles aux banques mais là, dans le cas de la variante "Up2Pay" utilisée par le Crédit Agricole, ils **exigent** que les champs obligatoires aient une valeur... (sous peine de désactiver le système de paiement)
Pour mémoire les champs obligatoires sont :
- FirstName
- LastName
- Address1
- ZipCode
- City
- CountryCode
_après, à priori il n'y a pas de contrôle de ces données si ce n'est le format donc rien n'empêche que le pipeline envoie des données bidon..._

**Comment by Cerdic** [comment]
corrigé dans la v6.2.0 donc

**Comment by jmoupah** [comment]
@cy-altern As-tu un lien vers la doc où ils exigent que les champs aient une valeur ? 
Pour l'instant, je ne remplis pas ces infos et ça fonctionne mais si ça devient problématique, il faudra que je change ça...

Mes clientes avaient également reçu le recommandé mais il est lacunaire (cf capture jointe) et le support ne m'avait pas indiqué l'obligation de remplissage (mais je n'ai pas posé la question).

![Presse-papier01](https://github.com/nursit/bank/assets/18148022/512cc7e7-6e33-4a59-b106-e93abf3196ea)

**Comment by jmoupah** [comment]
Je viens d'avoir confirmation par le support up2pay que les champs ne doivent pas être vides et que, à terme, les données seront vérifiées.

**Comment by Cerdic** [comment]
on adore le "à terme" : genre pour le moment on en fait rien mais un jour peut-être, en attendant on fait une erreur si vous remplissez pas l'info pour faire croire que c'est plus sécurisé...

Bref, on est bon donc
