### ISSUE TITLE
E-transactions (CA), idem Paybox mais urls différentes

### ISSUE THREAD

**Issue by nd-** [nursit/bank#121]
J'ai un client au Crédit Agricole qui utilise leur solution E-transactions.

C'est en fait Paybox, mais avec des urls de endpoint différentes : https://tpeweb1.paybox.com au lieu de https://tpeweb1.paybox.com, idem en preprod.

Actuellement, ça m'oblige à dupliquer paybox dans mon plugin et à tout renommer en etrans, juste pour changer une url.
Mais pour les mises à jour, c'est relou.

Je propose de mettre le domaine en constante surchargeable, PR à suivre.

**Comment by nd-** [comment]
Arf, erreur de copié collé, je voulais dire https://tpeweb.e-transactions.fr/ au lieu de https://tpeweb.paybox.com/

Mais pour toi ça marcherait direct ? 

Effectivement quand j'appelle https://tpeweb.e-transactions.fr/ depuis le navigateur ça me répond 
```
<html>
<body>
tpeweb.paybox.com - 24
</body>
</html>
```
Ils ont peut être une redirection derrière.

Je leur demande si ça peut fonctionner comme ça.

**Comment by Cerdic** [comment]
Ah cette URL me dit quelque chose, mais je pense que j'avais testé en gardant le serveur paybox d'origine et c'était bon.  Je pense que c'est juste du rebranding de domaine, et ça tape sur le même serveur derrière

**Comment by nd-** [comment]
Bon, j'attends une réponse de leur support...

**Comment by cy-altern** [comment]
étonnant : chez moi Up2Pay (nouvelle appellation de E-transaction du Crédit Agricole pour son implémentation de Paybox/Veriphone) fonctionne sans problème avec https://tpeweb.paybox.com

**Comment by nd-** [comment]
Réponse du support : 

> Vous pouvez tout à fait utiliser les URL natives à la plateforme Paybox que nous utilisons.
> Le seul risque vient du fait que nous n’avons pas de surveillante sur ces URL donc en cas d’incident sur cette URL, nous aurons l’informations que plus tardivement.

**Comment by Cerdic** [comment]
good, un problème de résolu ! :p

**Comment by nd-** [comment]
Par contre j'avais raté la subtilité qu'il fallait utiliser le pipeline bank_dsp2_renseigner_facturation pour renseigner les infos de facturation, mais j'aurai dû me douter, vu la multiplicité des cas possibles de gestion d'adresses.
