### ISSUE TITLE
Evénements Stripe

### ISSUE THREAD

**Issue by nd-** [nursit/bank#122]
Suite à mes commentaires ici : https://contrib.spip.net/Module-de-Paiement-Stripe#comment514231

Je note donc que les events de Stripe traités par Bank seraient : 

checkout.session.completed
customer.subscription.created
customer.subscription.deleted
invoice.payment.succeeded
invoice.payment.failed
invoice.payment.result

Côté Stripe, je ne trouve pas `invoice.payment.result`, il a peut être été supprimé dans la dernière version de l'API ?

Et pour un event non traité, /bank_api est censé répondre en 200 ?

Dans mon log Stripe je vois par exemple qu'il a appelé avec un event `charge.succeeded` et qu'on lui a répondu en 200

**Comment by Cerdic** [comment]
ça marche
