### ISSUE TITLE
Question: commenter tester les échéances sur les abonnements ?

### ISSUE THREAD

**Issue by JohnXLivingston** [nursit/bank#123]
Bonjour,

Je développe un plugin basé sur SPIP Bank.

J'aurais besoin de pouvoir déclencher des échéances de paiements récurrents à la demande, pour pouvoir tester mon plugin.

Je vois qu'il semble exister des choses sur la page "demo", mais je ne trouve pas de documentation claire.

En attendant, pour simuler, j'ai mis des boutons de debug dans mon code. Ceux-ci déclenche des échéances avec un code ressemblant à: 

```php
$preparer_echeance = charger_fonction('preparer_echeance', 'abos', true);
$id_transaction_enfant = $preparer_echeance("uid:" . $abo_uid);
if (!$id_transaction_enfant) {
    spip_log(__FUNCTION__.' Echec de preparer_echeance pour la transaction campagnodon '.$id_campagnodon_transaction, 'campagnodon'._LOG_ERREUR);
    return;
}
```

Mais ce code n'est pas exactement équivalent au chemin "normal": la transaction apparaît comme non payée, et je dois ensuite aller la marquer comme payée via l'interface de SPIP Bank.

J'aurais besoin de pouvoir déclencher à la demande, et plusieurs fois par jour, des mensualités (ou annualités).
Il faudrait que cela déclenche exactement les mêmes pipeline que dans un cas réel.
Pour info, mon client passe par payzen, via des virements SEPA.

Comment puis-je faire ?
Merci d'avance !

**Comment by Cerdic** [comment]
Pour tester les abonnements, déjà une bonne nouvelle : le plugin bank gère maintenant les récurences en interne si besoin, et donc le mode de paiement "Simulation" permet de tester complètement le paiement des abonnements, récurrences comprises.

Par contre pas de miracle : si on veut tester proprement on ne peut pas générer plusieurs récurrences d'abonnement par jour sur un même abonnement, car cela perturberait toutes les gestions de date.

Ce qui marche le mieux pour debug et faire la mise au point de ton code, c'est de générer un abonnement en récurrence journalière, ce qui permet déjà d'avoir une récurrence par jour et donc un test par jour/abonnement, et du peux évidemment tester avec plusieurs abonnements en parallèle.

Mais en effet donc, le debug&test de tout ce qui est abonnement est toujours long, car si tu peux dégrossir en simulant certains appels comme tu le fais, seul le process réel et temporel permet vraiment de tester proprement.
(et donc mon expérience, c'est que même en ayant debug sur de la récurrence journalière, il faut suivre les premières mises en production et renouvellements d'abonnement pour détecter les derniers bugs)

A noter que tu peux aussi regarder ce que font les plugins
- https://git.spip.net/spip-contrib-extensions/souscription
- https://git.spip.net/spip-contrib-extensions/commandes
- https://git.spip.net/spip-contrib-extensions/abonnements

**Comment by JohnXLivingston** [comment]
Dans mon cas, j'ai des différences entre récurrences mensuelles et annuelles à tester :/. Ça va être compliqué pour la phase de recette avec le client.

Et je n'ai pas non plus prévu de récurrence journalière. Mais peut être que je devrais en ajouter pour le debug, en effet. Surtout qu'avec les récurrences gérées en interne, dont j'ai découvert l'existance la semaine dernière, ça fonctionnera !

J'ai déjà pas mal étudié le plugin Souscription (le plugin que je fais le remplace, avec une contrainte: sortir les données perso de SPIP, entre autre pour limiter les risques de sécurité).

Merci pour les autres liens, je jetterais un oeil.

Et merci pour la réponse !

**Comment by rastapopougros** [comment]
@JohnXLivingston les plugins Abonnements et Dons font justement déjà cela à 95% : remplacer Souscriptions en : 
1) découpant  les deux fonctionnalités en deux plugins distincts pour pas avoir un plugin fourre-tout/usine alors que ce sont bien deux besoins totalement différents (certains sites ne veulent que l'un ou que l'autre ya aucune raison de les forcer ensemble)
2) ne préjugeant pas d'où on veut stocker les données personnelles, en se reposant sur le plugin Commandes, qui a maintenant une API abstraite "infos_clients" qui permet d'injecter/renseigner les infos même si ça vient d'ailleurs (un autre CVT interne comme le plugin Profils, ou un autre CVT enregistrant dans un service externe, ou peu importe)

**Comment by JohnXLivingston** [comment]
> @JohnXLivingston les plugins Abonnements et Dons font justement déjà cela à 95% : remplacer Souscriptions en :
> 
>     1. découpant  les deux fonctionnalités en deux plugins distincts pour pas avoir un plugin fourre-tout/usine alors que ce sont bien deux besoins totalement différents (certains sites ne veulent que l'un ou que l'autre ya aucune raison de les forcer ensemble)
> 
>     2. ne préjugeant pas d'où on veut stocker les données personnelles, en se reposant sur le plugin Commandes, qui a maintenant une API abstraite "infos_clients" qui permet d'injecter/renseigner les infos même si ça vient d'ailleurs (un autre CVT interne comme le plugin Profils, ou un autre CVT enregistrant dans un service externe, ou peu importe)


Ah mince, on avait raté ça en commençant le taf. Ça fait plus d'un an qu'on est en prod (je bosse juste sur des évolutions là).
Merci pour l'info.
