### ISSUE TITLE
Concurrences des hits serveurs et retour client

### ISSUE THREAD

**Issue by Cerdic** [nursit/bank#14]
Cas réel :
Il y a eu 2 retours IPN serveurs : le 1er en echec avec une erreur, puis quelques secondes plus tard le second réussi.

Sur le second hit serveur on marque le paiement comme réussi, puis on passe par tous les pipelines pour générer le message de succès, ce qui a pris 4 ou 5 secondes dans les logs (le temps de faire des opérations métier et de générer la facture).

Dans l'intervalle, et pendant ce traitement, le client revient sur le site. Comme le paiement est marqué "réussi" on ne fait rien et le redirige directement sur la page de succès, mais comme le traitement du hit serveur n'est pas fini, le message n'est pas à jour, et contient le message d'échec généré par le 1er hit serveur.

Donc problème de concurrence avec plusieurs fixs possibles :
1/ quand on marque le règlement réussi il faut vider le message, au cas ou
2/ peut-être avoir un statut un intermédiaire "processing" pendant le hit de traitement, pour que le hit concurrent se mette en attente jusqu'à avoir vraiment 'ok' dans le statut ?

**Comment by lddfr** [comment]
Ça parait pas mal un statut "en cours de traitement". Au moins on sait que ça travaille, c'est rassurant, même si on n'a pas encore le statut final.
