### ISSUE TITLE
Bank renvoie un code erreur 28 a CyberMut

### ISSUE THREAD

**Issue by Cerdic** [nursit/bank#15]
Nous vous informons que votre interface retour a emis un accuse de
reception INVALIDE et la commande a ete VALIDEE.

REQUETE EMISE PAR NOTRE SERVEUR : 
....
Methode retenue : POST
TPE : ccccc
Host appele : xxxx.org
Port : 80
CGI appele : /bank.api/cmcic/autoresponse/
Requete emise : 
...
Erreur 28

**Comment by Cerdic** [comment]
(détail des requêtes non divulgué ici mais dispo)

**Comment by Cerdic** [comment]
Bon erreur 28 ça doit etre un code interne a CMCIC car le plugin ne renvoie qu'un 0 ou 1 pour les cas d'erreur

**Comment by Cerdic** [comment]
Je ne reproduis pas en rejouant l'URL sur le site, la réponse du serveur est OK

**Comment by asmadr** [comment]
Bonjour,
Comment avez vous corrigé l'erreur svp ? j'ai le même problème avec paiement 3 fois. 
Merci
