### ISSUE TITLE
Problème de personnalisation du prénom et nom quand création de compte

### ISSUE THREAD

**Issue by rastapopougros** [nursit/bank#18]
Hello, 
j'ai vu que @Cerdic avait modifié un peu le code pour personnaliser le prénom et le nom dernièrement, et ça marche maintenant très bien pour les deux, merci beaucoup !

Mais je remarque un problème, et je ne sais pas quelle est la solution la plus logique.

Il s'agit du cas où on a personnalisé avec "session_prenom" et "session_nom" **et** qu'on vient de créer un nouveau compte pour le visiteur qui va payer.

Dans ce cas la session `id_auteur` **isset** (et vaut 0), MAIS en revanche, `id_auteur` _de la transaction_ est différent de `id_auteur` _de la sesssion_ : dans la transaction j'ai bien mis le `id_auteur` généré pour le compte nouvellement crée ! Mais dans la session c'est toujours "0".

Du coup ça ne passe pas le test, et ça n'utilise pas les deux personnalisations demandées. :( 

Du coup je vois deux possibilités : 
- est-ce que ton test devrait être modifié ?
- ou bien est-ce que le plus sympa serait de **connecter** (et activer) le nouvel utilisateur, directement après que la création soit finie ?

Il me semble que j'ai déjà vu ça, et je crois que c'était un truc de @Cerdic, mais je ne suis plus sûr. Je ne sais jamais comment ça se passe pour la connexion à appeler en PHP, il me semble qu'on a pas de doc pour ça, et pas vraiment d'API claire à appeler pour connecter volontairement telle personne (enfin en tout cas je ne sais pas faire).

Qu'en pensez-vous entre ces deux possibilités ?

**Comment by rastapopougros** [comment]
On me parle de `auth_loger()`, est-ce suffisant ? (y compris pour confirmer auto et changer le statut pour le bon)
``` php
// On récupère l'auteur qui vient d'être créé
$auteur = sql_fetsel('*', 'spip_auteurs', 'email = '.sql_quote(_request('email')));
$id_auteur = intval($auteur['id_auteur']);
// On connecte le nouvel utilisateur directement !
include_spip('inc/auth');
auth_loger($auteur);
```

**Comment by Cerdic** [comment]
Loger automatiquement l'auteur nouvellement créé est une bonne idée, d'un point de vue parcours utilisateur, mais ce n'est pas le plugin bank qui doit le faire car il ne sait pas si c'est légitime. 
La fonction ``` auth_loger() ``` sert à ça oui

**Comment by rastapopougros** [comment]
Oui oui, pardon, je parlais bien de **mon formulaire** qui va connecter le nouvel utilisateur dès que le compte est fini d'être créé. Et c'est effectivement ce que j'ai testé cet aprèm : ça a bien l'air de fonctionner !

La solution côté Bank c'était plus la première question, de savoir si le test devait être reformulé un peu pour prendre en compte quand même le cas où la transaction contient le bon id_auteur mais où le visiteur n'est *pas* connecté.

Mais bon, ça marche en le connectant… faut juste penser à reformuler l'email de confirmation d'inscription, qui du coup ne nécessite plus de lien à cliquer, etc.

(PS pour note : dans certains cas comme ça où on est à peu près sûr que c'est la bonne personne qui crée le compte, car ya peu de chance que ce soit faux si la personne doit faire un vrai paiement ensuite, ça pourrait être bien d'avoir un plugin SPIP plugNplay, qui connecte directement après les fonctions d'inscriptions - faut être sûr de pouvoir s'y insérer du coup - et qui surcharge l'email par défaut pour mettre juste les infos sans le lien. Comme ça quand on est dans le cas d'un site de commerce, avec un tunnel de ce genre, on aurait juste à activer ce plugin, et ça fait déjà une chose de moins à gérer personnellement…)

**Comment by rastapopougros** [comment]
> ça pourrait être bien d'avoir un plugin SPIP plugNplay

https://contrib.spip.net/Connexion-des-l-inscription
