### ISSUE TITLE
Payzen - abonnement 

### ISSUE THREAD

**Issue by YellowMart** [nursit/bank#19]
Hello,
Tout d'abord, merci beaucoup pour tous ces plugins!

J'ai un problème avec le **#FORMULAIRE_PAYER_ABONNEMENT** : il ne transmet pas les informations concernant l'abonnement, il manque les champs **vads_sub_**

Avez vous une idée de comment remédier à cela?

Merci d'avance,
Martin

**Comment by Cerdic** [comment]
Le plugin ne se suffit pas à lui même : il faut fournit les infos concernant l'abonnement via une fonction `abos_decrire_echeance` :
https://github.com/nursit/bank/blob/master/presta/systempay/call/request.php#L152

De manière générale ça marche en prod avec payzen et abonnement, sur le périmètre du plugin bank
