### ISSUE TITLE
404 : "Aucun squelette bank_retour_*.html"

### ISSUE THREAD

**Issue by stefdn** [nursit/bank#20]
Bonjour,

Après validation du formidable (form simple : nom, mail, 3 montants au choix), j'ai le montant et les boutons de choix de paiement qui s'affichent.
Jusque-là tout va bien (o:

Au clic bouton "Régler par ..." s'affiche une page 404, pour `bank_retour_ok`, `bank_retour_attente` ou `bank_retour_echec` (simulation)

Les fichiers sont pourtant bien là dans `contenu/` ou `content/` alors je ne sais pas trop où chercher le problème.

Config :
- SPIP 3.1.1 mutualisé (à la main) OU 3.1.1 non mutualisé, sur 2 serveurs : même chose
- Formidable 
  - Afficher ensuite : Rien du tout 
  - Traitements :  
    - Enregistrer les résultats + paiement OU 
    - Envoyer par courriel + Enregistrer les résultats + paiement 
- Bank : "master.zip" téléchargé depuis SPIP et renommé 'bank' dans plugins/auto
  - Notifications : les 3 champs remplis avec le même email
  - Prestataires activés (un seul à la fois ou ensemble, idem) :
    - Virement bancaire
    - Chèques
    - Simulation (notifications bien envoyées)

je rate un truc ou bien ?

**Comment by Cerdic** [comment]
les squelette de `contenu/` ou  `content/` ne seront utilisés automatiquement que si le site utilise zpip ou un squelette basé sur z-core.

Sinon il faut créer les pages concernées, en incluant éventuellement les squelettes de `content/` pour le coeur de la page
