### ISSUE TITLE
.htaccess obligatoire pour paypal express ?

### ISSUE THREAD

**Issue by phenix-factory** [nursit/bank#24]
Hello,

On a remarqué un comportement étrange : si le htacces n'est pas activé, le payement par paypal express échoue car bank utilise les URL .api qui sont dedans.

Du coup il faudrait prévenir l'utilisateur si son htaccess n'est pas activé.

**Comment by Cerdic** [comment]
normalement le plugin regarde si le fichier .htaccess est là et si il y a bien la RewriteRule sur les api avant d'utiliser ce type d'URL. Mais c'est vrai que si le fichier n'est pas pris en compte par apache ça bloque. Il faudrait un test plus robuste

**Comment by phenix-factory** [comment]
Peut être qu'il faudrai commencer par avoir une fonction qui test que le htaccess de SPIP fonctionne dans le core de SPIP. Ainsi, tout les plugins pourraient en profiter.

Peut être aussi qu'on pourrai personnaliser l'erreur des pages API pour qu'elles avertissent que le htaccess n'est peut être pas activé ?

J'ouvre un ticket pour le core ?

**Comment by Cerdic** [comment]
J'ai amélioré la detection de la présence de la rewrite rule, pour prendre en compte si elle est commentée ou non, mais il reste que le htaccess doit etre fonctionnel si il est présent, en effet 
(sinon c'est un cas un peu borderline, qu'on ne traitera pas ici, et qui de toute façon fera coincer toutes les méthodes de paiement)
