### ISSUE TITLE
Pouvoir spécifier les URL de retour dans l'appel des formulaires

### ISSUE THREAD

**Issue by rastapopougros** [nursit/bank#36]
Dans la doc, il est dit que les URL de retour peuvent être personnalisée uniquement dans le pipeline "bank_redirige_apres_retour_transaction".

Mais pourquoi uniquement par pipeline donc compliqué ? Ne pourrait-on pas pouvoir envoyer en params les URL voulues dès l'appel, donc en tant qu'intégrateur en squelettes, et non pas en tant que développeur PHP ? (ce ne sont pas forcément les mêmes personnes qui travaillent)

Dans #FORMULAIRE_PAYER_ACTE (mais pareil pour l'autre), on devrait pouvoir donner "url_retour_ok", "url_retour_attente" et "url_retour_erreur" en param.

**Comment by Cerdic** [comment]
parce que les urls de retour contiennent des informations sur la transaction (id_transaction, hash…) qui ne sont pas connues au moment de l'appel du formulaire ?

Il faudrait du coup pouvoir insérer des `@id_transaction@` dans l'URL que l'on fournit pour qu'elle soit complète in fine. Ça ne règle pas tous les cas, et le pipeline peut continuer à exister pour les cas complexes, mais en effet on pourrait ajouter ça à l'appel pour les cas simples

**Comment by rastapopougros** [comment]
Ok, mais les remplacements de variables dynamiques peuvent même être facultatives, en amélioration encore pour après. Puisque de toute façon actuellement on ne choisit même pas les pages vers laquelle on va. Là on pourrait donner les trois pages brutes, et ensuite le plugin fait comme actuellement pour page=bank_truc, il rajoute ses variables à lui, id_transaction, hash, etc.

**Comment by Cerdic** [comment]
Ah mais c'est déjà prévu comme ça en fait, cf le PhpDoc du formulaire :
https://github.com/nursit/bank/blob/master/formulaires/payer_acte.php#L19

J'ajoute l'url_retour_attente qui manque et ça sera bon

**Comment by Cerdic** [comment]
Et voila
