### ISSUE TITLE
Redirigé vers bank_retour_echec après paiement réussi via Paypal.

### ISSUE THREAD

**Issue by Gilles-L-Artaban** [nursit/bank#37]
Avec la version 3.6.7 sur un SPIP 3.2.4, je suis redirigé vers la page bank_retour_echec Paypal en mode test après un paiement réussi.
Avez-vous besoin d'autres informations pour résoudre ou au moins constater ce problème ?

Bien à vous.

**Comment by Gilles-A** [comment]
J'ai renseigné le IDENTITY_TOKEN et ça marche. Si ce champ est nécessaire pour le bon fonctionnement du plugin, il faut le rendre obligatoire ;-)

Bien à vous.

**Comment by Cerdic** [comment]
ah oui désolé. 
La gestion des champs obligatoire sur la configuration du plugin serait à améliorer, car actuellement aucun champs n'est obligatoire (c'est historique et lié au fonctionnement ancien du plugin). Je ferme ici
