### ISSUE TITLE
Plus de Pop-up pour stripe avec la V4.0.2 ?

### ISSUE THREAD

**Issue by Gilles-A** [nursit/bank#38]
Bonjour,

Je viens de passer à la V4.0.2  pour utiliser Stripe via votre plugin. Il semblerait que maintenant, on ne passe plus par un pop-up sur le site, mais que l'on sorte du site pour passer par une page de chez stripe. Est-il toujours possible d'avoir un pop-up comme avant ou bien doit-on obligatoirement "aller" chez stripe en pleine page ?

Merci d'avance de vos éclaircissements,

**Comment by Cerdic** [comment]
Stripe a complètement revu son workflow de paiement, et le fonctionnement en popin n'est plus possible avec les méthodes qui sont compatibles avec la SCA/DSP2

**Comment by Gilles-A** [comment]
Merci de ta réponse. 
Le plugin fonctionne donc maintenant en Checkout mais je vois que Stripe propose aussi Stripe Elements. Ce n'est pas compatible et intégrable au plugin ?
Que se passera-t-il si on garde la v3 du plugin, car le paiement sur le site est important ?
Cela va être pareil avec Payzen et Paybox ?
Cela fait beaucoup de questions... Merci d'avance de tes précisions.

**Comment by Cerdic** [comment]
Le plugin utilisait déjà Checkout, mais son intégration a changé chez Stripe pour prendre en compte la SCA. Je n'ai pas regardé Elements.

La version 3 du plugin utilise l'ancien checkout qui n'est pas compatible avec la SCA et va donc poser des problèmes de refus de paiement ou d'abandon plus importants et je ne sais pas si Stripe va continuer à assurer son fonctionnement.

Les APIs payzen et paybox n'ont pas été modifiées, mais leur intégration a été améliorée car on transmet maintenant plus d'infos sur l'acheteur quand elles sont disponibles (adresse facturation), pour améliorer la sécurité du paiement

**Comment by rastapopougros** [comment]
Ah tiens ce point m'intéresse, quand il y a des infos en plus du nom/emai envoyé à la banque (adresse etc), ça vient d'où, c'est récupéré à partir de quoi ? Et du coup est-ce que/comment c'est personnalisable ? (puisque ça pourrait venir de champs extras, du plugin livraison, du plugin coordonnées… suivant le workflow de chaque besoin)

**Comment by Cerdic** [comment]
Ça vient de https://contrib.spip.net/Plugin-Bank#bank_dsp2_renseigner_facturation

et deux exemples d'utilisation :
* https://github.com/nursit/livraison/commit/fb63293a67f8c60f79e6a3dd871f30cca30ce755
* https://github.com/otetard/spip_souscription/commit/8a02a57a2b0171d290a8f9bbb4b0200184fee7ca

**Comment by rastapopougros** [comment]
Super, merci !

**Comment by Gilles-A** [comment]
Merci Cerdic de test précision. En fait, nous cherchons un moyen de paiement avec un pop-in. Il y a en a-t-il encore avec le plugin Bank ? Si oui, lequel ou lesquels nous recommandes-tu ?
Merci d'avances de ta réponse !

**Comment by Cerdic** [comment]
Non, Stripe était le seul à proposer ce mode de fonctionnement à ma connaissance
Paradoxalement il semble que la popin ne soit pas si rassurante que ça. Les utilisateurs sont habitués à aller sur la page de paiement de la banque et font confiance à ce processus.

On a eu plusieurs retour sur la popin : les utilisateurs n'étaient pas si rassurés de filer leur CB au site (ou en tout cas c'est l'impression légitime qu'ils avaient)

**Comment by Gilles-A** [comment]
Merci pour cette réponse rapide qui nous éclair et nous donne une réflexion intéressante sur les pop-in pour les paiements.
