### ISSUE TITLE
Nom variable au lieu de sa valeur dans une success_url ( Stripe ) ?

### ISSUE THREAD

**Issue by Gilles-L-Artaban** [nursit/bank#42]
Bonjour,

Nous avons reçu un message la part de Stripe "Stripe webhook delivery issues". Apparement un webhook a été créé pour url de webhook donné par spip. Nous nous souvenons pas avoir créé ce webhook... Est-il créé par le plugin ?

Par ailleurs en regardant les "logs" des test des end point, pour un checkout.session.completed, il y a une url avec un paramètre "surprenant" : https://monsite.fr/bank.api/stripe-FDC7/response/?id_transaction=10&transaction_hash=116976777&sign=6a190be66d1d3e35b74f036fdd8587c1623ec8f7&session_id={CHECKOUT_SESSION_ID}. le {CHECKOUT_SESSION_ID} me surprend. On dirait le nom d'une variable au lieu de sa valeur. Je ne sais pas si le problème vient pas de là...

Qu'en pensez-vous ?

**Comment by Cerdic** [comment]
Le plugin bank créé en effet maintenant automatiquement le webhook dont il a besoin, pour être sur que tout va fonctionner.

Quand à l'URL du webhook elle est tout à fait normale, cf la section documentation ici https://stripe.com/docs/payments/checkout/fulfillment#webhooks
