### ISSUE TITLE
Le fomulaire de paiement ne s'affiche plus avec Stripe

### ISSUE THREAD

**Issue by Gilles-L-Artaban** [nursit/bank#43]
Lorsque Stripe est activé, le formulaire de paiement n'affiche plus rien. Si il y a seulement le paiement par chèque, le formulaire s'affiche.

Pour info, voici ce que j'ai dans les logs.

Vu dans stripe_test.log : :Pub:ERREUR: call_response : checkout_session_id invalide / no payment_id
Vu dans stripe.log : 2019-11-25 17:44:37 83.152.44.246 (pid 610) :Pub:ERREUR: stripe_set_webhook: Impossible de modifier le endpoint we_1Fii7KD9j7IwbtT20UsOZwz3 {"url":"https:\/\/mon-site.fr\/bank.api\/stripe-FDC7\/autoresponse\/","enabled_events":["*","checkout.session.completed"]} :: You may not specify other event types in `enabled_events` alongside '*'.

Qu'en pensez-vous ?

**Comment by Cerdic** [comment]
L'erreur sur le webhook a été corrigée par e3f9b952798b5fc3f2f25c3f195ba82c7769518c donc je suggère de mettre à jour le plugin pour commencer.

Mais sinon ça ressemble à une erreur Fatale, et il faut regarder les logs PHP ou Apache pour voir la nature de l'erreur

**Comment by Gilles-L-Artaban** [comment]
Merci de ta réponse ! Apparemment, c'était due à notre certificat qui n'était plus valide !
Bref, il vaut que je reteste pour valider ça.
Encore merci !

**Comment by Gilles-L-Artaban** [comment]
Je vais quand même mettre à jour le plugin dés que possible ;-)
