### ISSUE TITLE
Prise en compte des devises

### ISSUE THREAD

**Issue by tcharlss** [nursit/bank#48]
Ahoy,

Je rebondis sur la question posée ici : https://contrib.spip.net/Plugin-Bank#comment489776-489429

Si jamais il y a une évolution de prévue dans bank pour communiquer les devises aux plateformes de paiement, les dernières évolutions du plugin prix pourraient être prises en compte.

À partir la v1.1, il y a un début de gestion des devises.
Ça ne permet pas encore de faire du multi-devises, mais on peut au moins définir la devise par défaut du site, et celle-ci est utilisée pour l'affichage des prix. Les 2 constantes `PRIX_DEVISE` et `DEVISE_DEFAUT` ont été retirées, ça se fait dans la configuration du plugin.

Les 2 fonctions utiles :

* [`prix_devise_defaut`](https://git.spip.net/spip-contrib-extensions/prix/src/branch/master/prix_fonctions.php#L266) renvoie la devise principale du site (code alphabétique à 3 lettres norme ISO 4217)
* [`prix_lister_devises`](https://git.spip.net/spip-contrib-extensions/prix/src/branch/master/prix_fonctions.php#L200) renvoie la liste des devises avec toutes les infos (codes alphabétiques et numériques, nom, etc.)

**Comment by tcharlss** [comment]
Ps. : cette version de prix étant encore en dev, on peut toujours renommer/réorganiser les onctions si besoin. C'est juste pour dire que la fonctionnalité est là.

**Comment by rastapopougros** [comment]
Voilà pour ce ticket là : https://github.com/nursit/bank/pull/52

**Comment by Cerdic** [comment]
Je ferme ici vu qu'on a la PR et la branche dev/v5 pour ça
