### ISSUE TITLE
Question ou bug pour la prise en compte des centimes dans Ogone

### ISSUE THREAD

**Issue by rastapopougros** [nursit/bank#50]
Hello, je pose la question à tout hasard, car je n'arrive pas à trouver la doc de la version de l'API utilisée, pour y répondre moi-même sans déranger. :)
Donc je préfère demander si jamais il s'agit d'un bug.

Pour Ogone, l'API attend le montant dans la plus petite unité (le centime pour l'euro). Donc Bank multiplie par 100 avant de faire la requête et remplir la clé "amount".

Mais ensuite dans la réponse, c'est toujours la même clé "amount", et donc je supposais que ça revenait **aussi** en centimes, vu que même API et même clé. Mais là pour comparer avec spip_transactions qui a un montant en euro, ya pas de division par 100.
https://github.com/nursit/bank/blob/master/presta/ogone/inc/ogone.php#L286

Pour Systempay qui attend aussi des centimes en requête, et bien lors de la comparaison de la réponse, là il y a bien une division par 100.
https://github.com/nursit/bank/blob/master/presta/systempay/inc/systempay.php#L380

Alors oubli donc bug ?

**Comment by Cerdic** [comment]
C'est du code qui a tourné (tourne encore ?) en production, donc je pense pas qu'il manque une division par 100

Tu as un exemple de réponse du serveur https://github.com/nursit/bank/blob/master/presta/ogone/inc/ogone.php#L228 et j'ai bien l'impression que c'est 7€ et pas 7 centimes dans la réponse.

Il faudrait ressortir la doc, ou même avoir une doc à jour, car je sais pas si l'API a changé depuis le temps, mais a priori non pas d'oubli ni de bug - sous réserve.

(Ça fait longtemps que je ne m'étonne plus de l'inconsistance des API bancaires, c'est franchement pas les plus exemplaires...)

**Comment by rastapopougros** [comment]
Oui c'est pour cela que je cherchais la doc, pour savoir si c'était une API pourrie qui attendait des centimes en entrée, mais retournait des euros. :)

Mais tant mieux si tout va bien !

**Comment by Cerdic** [comment]
La donc est donc là et c'est indiqué en page 17 : le retour se fait bien en euros, et pas en centimes, il n'y a pas de bug

**Comment by Cerdic** [comment]
là https://www.nursit.com/IMG/pdf/ogone_e-com-bas_en.pdf
