### ISSUE TITLE
Paypal Express : paiements récurrents

### ISSUE THREAD

**Issue by tcharlss** [nursit/bank#51]
Hello,

On fait un dev pour l'édition chilienne du monde diplo : il leur faut à la fois des paiements à l'acte et récurrents. Et à priori le seul presta qui conviendrait pour ce pays c'est Paypal Express.

Alors avant d'envisager faire évoluer ce presta dans Bank pour ajouter les paiements récurrents, c'était pour voir avec toi s'il y avait des choses à savoir en particulier.

Par exemple si jamais ça n'avait pas encore été implémenté pour une raison précise (manque de documentation, ou des choses bloquantes, je sais pas...), comme ça on évitera de se lancer dedans pour rien.

Mais s'il n'y a rien de notable, on se propose d'ajouter ça donc.

**Comment by Cerdic** [comment]
non rien de notable, juste le fait que j'ai jamais eu de cas où c'était nécessaire, et l'expérience m'a montré qu'il faut absolument avoir une appli réelle pour développer une api presta bancaire pour être sur de bien tester, et surtout en paiement récurrent : il y a plein de petits cas limites qu'on voit qu'en prod...

(Attention à vous, prévoyez du temps pour faire du support&debug en prod post-codage, car il y aura toujours de problèmes ponctuels. Mon expérience c'est que le paiement récurent a toujours besoin d'un peu de suivi/TMA, contrairement au paiement unique qui en général ne pose jamais de soucis une fois en prod)

**Comment by tcharlss** [comment]
Ok super, merci pour les infos.

**Comment by rastapopougros** [comment]
Mais apparemment Paypal Express c'est déprécié depuis… plus de 3 ans déjà. Donc je sais pas si ça a un intérêt d'essayer d'ajouter les paiements récurrents dessus. :(
https://developer.paypal.com/docs/archive/express-checkout/

Maintenant c'est une API REST, et ya une "subscriptions API".

**Comment by tcharlss** [comment]
Oui donc on peut fermer je pense :)

Les amis du diplo n'ont pas donné suite, et si c'est le cas plus tard le dev se ferait sur un nouveau moyen de paiement donc (un autre paypal).
