### ISSUE TITLE
Écrasements de transactions dons mensuels SDD/SEPA avec PayZen

### ISSUE THREAD

**Issue by ValentinDrean** [nursit/bank#59]
Bonjour,

D'abord merci pour tout le travail accompli sur Spip Bank, ce plugin est tout-à-fait efficace pour tout ce dont on peut avoir besoin dans une association s'il est couplé avec Spip Souscription, ce qui est ici mon cas :)

Je suis passé de TEST à PRODUCTION avec PayZen comme middleware sans trop de souci pour les paiements ponctuels, par contre pour les paiements mensuels via SDD/SEPA c'est déjà + compliqué, je ne suis pas sûr que cela soit une issue à proprement parlé, désolé si la forme n'y est pas.

Je me suis d'abord permis de modifier quelques bouts de code dans Spip Bank afin que cela colle à mes besoins :

 - Règle d'abonnement changé à `BYMONTHDAY=5` (`presta/systempay/call/request.php`)
 - signature au format base64 hashé en sha256 au lieu de sha1 (`presta/systempay/inc/systempay.php`, cela m'a été demandé par PayZen, inspiré de https://payzen.io/fr-FR/form-payment/standard-payment/calculer-la-signature-de-l-ipn.html)
 - `vads_sub_effect_date` baissé à 14 jours (`presta/systempay/call/request.php`, 14 jours étant le minimum proposé par PayZen)
 - nombre de jours de pré-notification côté PayZen réduit à 2 jours après demande explicite auprès d'eux
 - aucune modification dans `abos/decrire_echeance.php`, cela ne correspondait pas à mes besoins

Je n'ai aucun retour d'erreurs côté PayZen, j'en ai eu pendant le mode de TEST (décalages horaires UTC et problèmes de signatures base64+sha256) mais ceux-ci ont rapidement été résolus.

Mon problème arrive au moment de la réception de l' « URL de notification à la création d'un abonnement » provenant de PayZen et reçue par Spip Bank.

Dans mon cas, lorsque le formulaire de paiement SEPA/SDD est bien validé, celui-ci utilise `REGISTER_PAY_SUBSCRIBE` dans `vads_page_action` (au lieu de `REGISTER_SUBSCRIBE`) et fait un 1er paiement (et non une échéance d'abonnement), or d'après `presta/systempay/readme.md` il semblerait que cela ne soit pas possible pour le SEPA/SDD (je ne me sers pas des paiements CB mensuels ou annuels), ce que je ne comprends pas bien.

Ensuite, lors de l'arrivée de la première échéance d'abonnement via l' « URL de notification à la création d'un abonnement » provenant de PayZen (cette notification doit ajouter une nouvelle transaction), il arrive que cette transaction écrase la toute première transaction (qui n'est pas une échéance et qui accompagne la validation du formulaire SEPA/SDD comme expliqué dans le paragraphe précédent), or je ne comprends pas pourquoi. Cela résulte en un mauvais nombre de transactions. Il y a d'autres rares cas de figure ou les transactions en erreurs sont à leur tour écrasées (ce qui en soit est moins grave). Je n'ai constaté ce problème uniquement lorsque Spip Bank est passé en mode PRODUCTION, sinon c'est pas drôle :)

À partir de ce constat, je n'ai pas compris quelle est la cause générant ces écrasements, dois-je remettre la valeur par défaut de la date d'effet des 14 jours pour la remettre à celle d'origine ? Ou bien forcer le workflow de `REGISTER_PAY_SUBSCRIBE` à `REGISTER_SUBSCRIBE` ? Si oui : ou et comment ?

Par ailleurs j'aimerai spécifiquement garder ma règle d'abonnement `BYMONTHDAY=5` et je n'ai pas du tout besoin de la 1ère transaction au moment de la validation du formulaire.

Versions utilisées :

 - Banque&paiement 4.3.4 
 - Souscription 2.5.8
 - SPIP 3.1.6 [23598]

En supplément, voici mes règles de notifications côté PayZen :

 - URL de notification à la création d'un abonnement
Évènement(s) déclencheur(s) : Nouvelle échéance d'un abonnement
 - URL de notification à la fin du paiement
Évènement(s) déclencheur(s) : Paiement accepté, Paiement refusé, Création d'un abonnement, Création d'un alias, Mise à jour d'un alias
 - URL de notification sur une opération provenant du Back Office (pas utilisé pour l'instant)
Évènement(s) déclencheur(s) : Paiement accepté, Création d'un alias, Mise à jour d'un alias, Paiement refusé, Transaction modifiée par le marchand ou l'acquéreur, Transaction validée par le marchand, Transaction dupliquée par le marchand, Transaction remboursée par le marchand, Transaction annulée à l'initiative du marchand

Je peux pousser le code modifié de Spip Bank quelque part si celui-ci est nécessaire pour aller + en profondeur, j'ai également de nombreux logs détaillés des différentes URL de notifications provenant de PayZen, je peux aussi ajouter de nouveaux spip_log dans le code si besoin.

Merci d'avance pour m'avoir lu, désolé pour la longueur et la forme, je ne voyais pas comment faire autrement, et merci pour l'aide le cas échéant !

Ps : toutes les « response » reçues côté PayZen on une sorte de souci de format : `SENT, rule=URL de notification à la fin du paiement, duration=~0,4s, response= ��������������������`, ça c'est une vraie issue, mais c'est autrement moins important :)

**Comment by Cerdic** [comment]
Salut @ValentinDrean !

Désolé, ma réponse va être décevante, mais : 
- d'expérience, tout ce qui est paiement récurrent est généralement pas vraiment testable en mode TEST car on a pas toutes les conditions identiques à la prod, et notamment donc, les paiement récurrents en vrai condition :p 
- le paiement récurrent, que ce soit SEPA ou pas, c'est toujours compliqué à debug car tout se passe sur du serveur à serveur, et on a que les logs pour essayer de comprendre
- de ce fait chaque modif est compliquée à tester, debug, valider - à chaque modif il faut attendre l'arrivée d'une échéance suivante présentant le même problème pour itérer dans l'analyse et la correction du bug, ce qui peut prendre 1 mois quand on en début de mise en service...
- de ce fait je n'implémente que des choses que je suis en mesure de tester et de suivre en live en prod pour la validation

Là, vu que tu as modifié la logique interne, je serai bien en peine de te dire ce qui ne marche pas, et encore moins de reproduire le soucis vu que je ne vais pas toucher à ça sur un site en prod...

Dans ce cas il faut lire le code et suivre ligne à ligne ce qui se passe en essayant de comprendre les conditions qui provoquent le bug, ajouter plein de logs où tu as des doutes, et attendre la prochaine occurrence du bug pour comprendre.

En parallèle je mets en place une fonction de réparation pour réparer manuellement en base ce qui s'est passé de travers après chaque incident jusqu'à ce que le bug ait été trouvé. Mais dans le cas de la suppression d'information c'est un peu chaud je te le concède...

**Comment by ValentinDrean** [comment]
Salut @Cerdic , 

J'aurai probablement dû mettre en PROD en catimini et attendre un mois donc, tant pis, dans tous les cas je me m'attendais pas à une réponse toute faite, merci d'avoir répondu.

À l'occasion, je pense que j'essaierai sur le site de dev' de forcer l'utilisation de `REGISTER_SUBSCRIBE`, je n'avais déjà pas touché au code au tout début des tests que `REGISTER_PAY_SUBSCRIBE` était visiblement déjà en place, ce qui est l'opposé de ce qu'indique le `presta/systempay/readme.md`.

J'indiquerai mes avancées sur cet issue, si cela peut en aider d'autres :)

**Comment by Cerdic** [comment]
Je pense que le problème vient de Souscription en fait, ici
https://github.com/otetard/spip_souscription/blob/master/souscription_pipelines.php#L381

Si le paiement d'une échéance arrive moins de 15j après le paiement précédent on se dit que c'est anormal et on renvoie le id_transaction de l'échéance précedente, ce qui dans ton cas doit correspondre à un cas limite.

Essaye avec un délai de 7jours ici ?

**Comment by ValentinDrean** [comment]
Excellent, ça a du sens, je viens de remplacer les deux occurences de `$datem15` en `$datem7` ainsi que son strtotime comme ci-dessous :

`$datem7 = date('Y-m-d H:i:s',strtotime("-7 day",$_SERVER['REQUEST_TIME']));`

Ai-je besoin de changer `$datep15` ligne 400 ?

À nouveau : merci beaucoup !

**Comment by ValentinDrean** [comment]
Échéance passée, ça ne marche pas non plus avec ce patch sur `souscription_pipelines.php#L381`, après une petite inspection des transactions concernées, il semblerait que les transactions « écrasées » sont systématiquement celles dont le formulaire SEPA a été validé entre le ~8 et le 22 (avant 8h) du mois. 

Aussi, la seule transaction systématiquement écrasée est la première, celle qui n'est pas une échéance donc, son `autorisation_id` ressemble à un RIB (ex : SOGEFRPPXXX/FRXXXXXXXXXXXXXXXXXXXXXXXX), les suivantes (vraies échéances) ont le format classique avec le 1er numéro de transaction suivi d'un hash qui je crois provient de PayZen, le `vads_trans_uuid`, bref (ex : XXX/5a88be8810794f769149549dd67d5af4).

Les transactions passées du 22 au ~6 n'ont pas ce problème.

J'essaierai de m'y replonger d'ici à l'échéance du mois prochain mais pour l'instant je sèche à nouveau.

**Comment by Cerdic** [comment]
Je ferme ce ticket parce que c'est vieux et ça concerne du code modifié sur lequel j'ai pas trop de visibilité...
