### ISSUE TITLE
Payzen arrête le webservice SOAP

### ISSUE THREAD

**Issue by Cerdic** [nursit/bank#64]
> IMPORTANT : Cet email est à destination de votre équipe technique en charge de votre site e-commerce.
>
> Cher client,
>
> Pour la réalisation de paiement sur votre site e-commerce, vous utilisez actuellement la technologie Web Services SOAP (Simple Object Access Protocol) mise à disposition par notre plateforme de paiement.
>
> Afin de vous offrir un service toujours plus performant, notre équipe a développé les mêmes fonctionnalités dont la technologie Web Services REST (REpresentational State Transfer).
>
> La technologie des Web Services REST offre les avantages suivants par rapport aux Web Services SOAP (Simple Object Access Protocol) que vous utilisez actuellement :
>
> Une technologie plus récente. Plus rapide car aucun traitement étendu n’est requis. Efficace en utilisant des formats de message plus petits par rapport au XML. Offre de meilleures évolutions. Simplicité de l’intégration. A la suite de cette évolution, les Web Services SOAP ne seront plus actifs à partir du 01 janvier 2023. Votre site ne pourra donc plus communiquer avec notre plateforme de paiement.
>
> Nous vous invitons à modifier votre intégration vers notre plateforme de paiement au plus vite.
>
> Une nouvelle intégration technique à prendre en compte
>
> L’ensemble de notre documentation sur les Web Services REST est disponible depuis notre site en ligne : 
>
> https://payzen.io/fr-FR/rest/V4.0/api/reference.html
>
> Une interface interactive vous accompagnera afin de vous faire gagner du temps lors de l’intégration.
>
> Pour tester rapidement les Web Services REST, n’hésitez pas à vous appuyer sur https://payzen.io/fr-FR/rest/V4.0/api/quick_start_api.html
>
> Nous vous conseillons fortement de prendre contact avec vos équipes techniques afin de mettre en œuvre l’ensemble des processus techniques liées à l’intégration des Web Services REST.
>
> Notre support technique reste à votre disposition pour vous accompagner dans ce changement.

**Comment by ValentinDrean** [comment]
> A la suite de cette évolution, les Web Services SOAP ne seront plus actifs à partir du 01 janvier 2023. Votre site ne pourra donc plus communiquer avec notre plateforme de paiement.

-> Ouf, 1er janvier 2023, le sujet de l'issue m'a donné un coup de chaud (:

**Comment by Cerdic** [comment]
Pris en charge avec la version 4.5.1 du plugin.
Il faut renseigner les password d'API REST qu'on trouve dans l'interface Payzen pour passer sur l'API REST (sinon ça reste sur le SOAP tant qu'elle marche encore)
