### ISSUE TITLE
Format invalide pour le(s) champ(s) /contexte_commande/shipping

### ISSUE THREAD

**Issue by JLuc** [nursit/bank#67]
Un utilisateur témoigne sur spip user :

Pour un site sous Spip 3.2.8, avec le plugin Bank 4.6.0  et PHP 7.0.33
Un formulaire formidable avec un champ de paiement
Le "prestataire" Monetico (banque CCM) activé dans le plugin Bank

Le remplissage du formulaire se passe correctement.
Suite à l'envoi vers Monetico, la réponse est : "Tous les champs requis sont présents.
Format invalide pour le(s) champ(s) : /contexte_commande/shipping"

De ce que je comprends du "contexte shipping" il attend une adresse (qui est pourtant présente dans le formulaire) :
https://www.monetico-paiement.fr/fr/info/documentations/Monetico_Paiement_documentation_technique_v2.0.pdf

En explorant les fichiers du plugin Bank, en particulier "request.php" : bank\v4.6.0\presta\cmcic\call\request.php.
Ligne 176 :
```
175        // obligatoire mais tous les champs sont optionnels (ou obligatoire 'si applicables' -> on laisse tout vide)
176       'shipping' => [],

```
N'ayant rien à perdre, j'ai commenté cette ligne 176 : ce qui m'a permis d'accéder enfin à la page de paiement de Monetico et valider le paiement en ligne.

**Comment by Cerdic** [comment]
Confirmé sur un site qu'on gère, et corrigé donc
