### ISSUE TITLE
Règlement chèque et pré-remplissage du montant si formatage par Intl

### ISSUE THREAD

**Issue by rastapopougros** [nursit/bank#76]
Quand on a la librairie Intl, le montant est formaté de manière plus complète suivant la langue, la devise, avec des meta données, etc.

Mais le form encaisser_reglement utilise le formatage *humain/sémantique* directement tel quel pour remplir l'input, alors qu'il faut juste le montant seul. Du coup on se retrouve avec dedans, tel quel : `<span class="montant" data-montant-nombre="30" data-montant-devise="EUR">30,00</span>`

Ça ne doit pas être grand chose mais il faudrait à minima faire un supprimer_tags avant insertion dans le champ.

**Comment by pierretux** [comment]
Bonjour,
Le problème se trouve sur tout les modes de paiement en fait.
Comment le corrigé ?

Merci

**Comment by pierretux** [comment]
oui c'est cela, les 2 plugins à jour ;)

**Comment by rastapopougros** [comment]
Oui et non pour Intl c'est qu'un exemple (de formatage *plus complet*). Si on a sa propre implémentation de `montant_formater`,  avec de l'affichage des montants qui fait du HTML, du formatage plus complet, c'est exactement le même problème. Donc c'est *une* possibilité de le voir (courante car Intl est obligatoire pour Prix et les trucs de commerce), mais ça peut se reproduire à minima même avec une fonction perso… qui n'a pas forcément ces options de Intl.

Le principe général pour corriger c'est que tout input où on met un prix doit s'assurer que c'est un *montant brut* et pas un affichage humain.

Au passage ya le second problème avec les chaines de langue et la sécurité bancale de SPIP sur le HTML (qui reconnait *rien* de HTML5), mais faut sûrement faire un ticket dédié (je le mets là car j'y pense). Là la solution (tant que la lib HTML de SPIP est pourrie, donc encore un moment) c'est : quand le formatage humain du montant est inséré dans une chaine de langue (sécurisée par défaut), appeler _T avec l'option pour désactiver la sécurité, vu que c'est pas truc libre, on sait que c'est un montant vérifié, ya pas de soucis de sécurité, ce qui évite de lancer le test HTML sur les params des chaines de langue. Donc concrètement ne pas appeler : `<:bank:info_cheque_imprimer{montant=#GET{montant}…` mais appeler `[(#VAL{bank:info_cheque_imprimer}|_T{#ARRAY{montant etc params}, #ARRAY{sanitize, 0}})]`

**Comment by Cerdic** [comment]
oui sauf que montant_formater est susceptible de faire tout et n'importe quoi, y compris avoir 2 fois le montant dans des spans différents si j'en crois la proposition de https://git.spip.net/spip-contrib-extensions/intl/issues/4 et c'est clairement pas bank qui peut/doit savoir comment défaire ça, et bien la fonction montant_formater qui doit quand même prendre en compte les options `markup` et `currency_display`...

**Comment by Cerdic** [comment]
bon j'ai amendé pour nettoyer du mieux qu'on peut côté bank, mais si il reste des soucis ce sera aux implémentations montant_formater de corriger leur comportement !

**Comment by Cerdic** [comment]
Écoute le problème est simple : il y a un formulaire pour que les gens saisissent le montant du règlement, pré-rempli puisque a priori on connait le montant, mais modifiable. C'est un montant monétaire, donc on veut le formater humainement correctement, avec le bon séparateur de décimal et le bon nombre de décimal. Donc pour se faire on utilise la fonction de formatage des montants, sans unité parce que on veut juste saisir un montant.

Pour des raisons x ou y vous avez voulu que cette fonction de formatage soit extensible, surchargeable et puisse générer des trucs fancy et riches. Soit.

Alors oui en effet, du coup il faudrait 2 options à la fonction : sans unité et ou sans html. Il se trouve que on a que 2 usages de cette fonction : soit pour avoir un affichage html joli, et on veut tout, soit pour avoir le montant uniquement, ce qui historiquement s'obtenait via `$unite=false` vu que c'était le seul enrichissement. Donc j'ai en effet décidé que cette option revenait aussi à dire "pas de html".

Donc maintenant je fais quoi ? 
* Je recode une fonction de formatage pour avoir un nombre tout seul (mais quand même bien formaté) ? 
* ou on convient que la fonction de formatage a une option (et la respecte) pour produire le montant bien formaté (décimales et séparateur) mais sans une tonne de html autour ?

Ou alors j'attends une PR qui fera le job suffisament bien à tes yeux et que je pourrai critiquer à ma guise vu que moi j'ai pas le bug de toute façon ?...

bref

**Comment by pierretux** [comment]
Re,

non j'ai encore le soucis

```
Transaction : #22
Montant : ⚠️ <b><span class="montant" data-montant-nombre="40" data-montant-devise="EUR">
40,00 <span class="montant__devise">EUR</span>
<meta itemprop="price" content="40" />
<meta itemprop="priceCurrency" content="EUR" />
</span></b>
```

**Comment by rastapopougros** [comment]
Mmmh @pierretux à priori là tu confonds avec l'autre bug (qui est un bug du vieux sanitazer HTML de SPIP), et qui est décrit ici : https://git.spip.net/spip/spip/issues/4706 (et donc la solution donnée plus haut serait de sanitize=false sur les chaines de langue contenant des montants).

Mais le ticket ici présent n'a rien à voir, c'est sur *l'input* du form "encaisser_reglement" pour les admins. Pas du tout les forms de paiement du public.

**Comment by pierretux** [comment]
en effet et je n'ai pas le soucis dans le formulaire

mais du coup il faut le faire au niveau de bank ce que tu indiques ?

**Comment by rastapopougros** [comment]
> pour ceux qui ont le problème, est-ce que #91 corrige bien en pratique le soucis ?

Comme dit au-dessus : "Pour ce qui est de la solution actuelle côté Bank, moi tout seul ça me convient ton commit"

Et j'ai testé pour de vrai dans un site, ça fait bien "10,00" sans tout le html.

**Comment by Cerdic** [comment]
intégré, en ajoutant un argument séparé pour l'option texte brut
