### ISSUE TITLE
Gestion du montant_init dans stripe pour les abonnements.

### ISSUE THREAD

**Issue by BoOz** [nursit/bank#80]
Les méthodes payzen et stripe gèrent un `montant_init` éventuellement différent du montant de l'échéance.

https://github.com/nursit/bank/search?q=montant_init

Sauf qu'a la différence de `Payzen` [ici ](https://github.com/nursit/bank/blob/master/presta/payzen/call/request.php#L250) l'implémentation pour `Stripe` ne vérifie pas que `montant_init>0` or à la base il est définit à zéro dans `abos_decrire_echeance_dist()`.

Bilan, si on ne dit rien du montant_init, Stripe va générer un coupon et offrir le premier prélèvement.

**Comment by Cerdic** [comment]
Corrigé donc

**Comment by BoOz** [comment]
Chez moi ca marche, merci.
