### ISSUE TITLE
Quand il n'y a qu'un seul moyen de paiement

### ISSUE THREAD

**Issue by baroug** [nursit/bank#82]
Hello, dans le modèle payer acte https://github.com/nursit/bank/blob/master/modeles/payer_acte.html
on a cet h3 [(#ENV*{title,<:bank:titre_mode_paiement_securise:>})]
Il est suppopsément possible d'en changer le title mais le problème c'est qu'il est appelé par d'autres modèles et inclure qu'on ne peut pas modifier pour l'occasion. Aussi je suggère ceci :

```
<h3 class='selectionnez'>
		[(#COMPTEUR_BOUCLE|>{1}|?{
			[(#ENV*{title,<:bank:titre_mode_paiement_securise:>})],
			[(#ENV*{title,<:bank:titre_proceder_paiement_securise:>})]
		})]
</h3>
```

Qui mettrait la chaine fictive <:bank:titre_proceder_paiement_securise:> (qui afficherait par ex en fr "Procédez au paiement :") dans le cas d'un seul moyen de paiement sélectionné auparavant.

Cette solution à base de #COMPTEUR_BOUCLE est peut être merdique pour diverses raisons mais un truc du genre serait bienvenu il me semble.

**Comment by baroug** [comment]
(J'ajoute que dans ma « solution », si le fait de mettre un message qui sélectionne pas dans un h3.selectionnez c'est un blasphème, on peut mettre la balise dans la conditionnalité j'imagine)

**Comment by BoOz** [comment]
J'ai fais une PR avec tout ca : https://github.com/nursit/bank/pull/83/files

**Comment by Cerdic** [comment]
Intégrée !
