### ISSUE TITLE
Problème de Hash avec Paybox

### ISSUE THREAD

**Issue by sebPA06** [nursit/bank#85]
Bonjour à tous, je me permet de vous écrire car je rencontre un soucis avec la dernière version du plugin Bank (5.0.7) et Paybox. 

Voici l'url d'un des formulaires de paiement : https://www.petitesaffiches.fr/annonces-legales-france,057/offres-d-abonnement-et-de-services,066/abonnez-vous-au-service-ventes-aux,7108.html

Deux erreurs semblent remonter : le champs PBX_PORTEUR n'était pas rempli. J'ai ajouté un flag directement dans le module pour palier à ce problème pensant résoudre temporairrement le problème : 

Ligne 237 du fichier /plugins/auto/bank/v5.0.7/presta/paybox/inc/paybox.php
`if($k == 'PBX_PORTEUR'){
                        $hidden[] = "<input type=\"hidden\" name=\"$k\" value=\"abonnement@petitesaffiches.fr\" />";
                    }else{
                        $hidden[] = "<input type=\"hidden\" name=\"$k\" value=\"$v\" />";
                    }`

Après ce problème, un autre survient : l'arrivée sur la page paybox remonte l'erreur "Problème d'identification du commerce.
Accès refusé !". 

Les identifiants et clé HMAC sont correctes (ils fonctionnent sur un prestashop notamment). 

Il y aurait donc un problème du calcul du hash d'après le support Paybox. 

Merci d'avance pour toute aide ou contribution apportée.

**Comment by Cerdic** [comment]
Il faut retirer le patch, c'est lui qui provoque l'erreur de calcul du hash et le refus d'accès. Le formulaire est signé et le hash de signature est calculé en amont, donc il n'est pas permis de modifier le formulaire comme ça

Ton problème vient surement de la dernière modif
https://github.com/nursit/bank/commit/745d9bb5d1e26bf2416e2e04fef5802228486548#diff-280ad9a181a4e40f58157217e2f324cc101bc6d1741f596f40200568b3d4a4f3
mais normalement la fonction https://github.com/nursit/bank/blob/master/inc/bank.php#L406 s'arrange pour toujours fournir un email

Peux-tu décommenter la ligne 
https://github.com/nursit/bank/blob/master/inc/bank.php#L443

et me dire ce que cela log dans tmp/log/dspdbg.log après un affichage du formulaire de paiement ?

**Comment by sebPA06** [comment]
Bonjour Cedric, merci pour la réponse. J'ai restauré le patch et j'ai donc de nouveau le message " Erreur de protection.
Nous regrettons de ne pouvoir donner une
suite favorable à votre demande de paiement."

J'ai décommenté la ligne indiquée et ai tenté un paiement mais pas de fichier dspdbg.log dans mon répertoire tmp/log/. Il s'agit bien du répertoire tmp à la racine du SPIP ? 

Merci d'avance.

**Comment by Cerdic** [comment]
Il faut ajouter la ligne suivant dans ton fichier `config/mes_options.php`
```
define('_LOG_FILTRE_GRAVITE',7);
```
pour avoir tous les logs

**Comment by sebPA06** [comment]
Merci pour cette réponse. En effet cette fois-ci, les logs s'affichent bien. 

Voici ce qui est loggué : 
`2022-01-07 11:11:13 90.8.167.189 (pid 1365676) :Pub:info: bank_porteur_infos_facturation:4554:{"nom":"EDITEUR","prenom":"","email":"20","adresse":"","code_postal":"","ville":"","etat":"","pays":""}
2022-01-07 11:11:40 90.8.167.189 (pid 1365672) :Pub:info: bank_porteur_infos_facturation:4555:{"nom":"EDITEUR","prenom":"","email":"20","adresse":"","code_postal":"","ville":"","etat":"","pays":""}`

**Comment by Cerdic** [comment]
Tu as donc un plugin (perso ?) qui renseigne les infos dans le pipeline `bank_dsp2_renseigner_facturation` en y mettant la valeur `20` en guise d'email.

Ce pipeline sert à renseigner les informations concernant le payeur, qui sont ensuite utilisé par le prestataire bancaire puis transmises à la banque pour que celle-ci détermine si le paiement par carte semble normal ou si il semble plus prudent de déclencher une authentification forte.

Il convient donc de renseigner correctement les infos dans ce pipeline pour assurer la fluidité des paiements en ligne

**Comment by Cerdic** [comment]
Ah tu utilises visiblement le plugin formidable_paiement, qui renseigne ce pipeline via ce que tu lui as renseigné dans le traitement du formulaire. Il y a un select pour désigner le champ qui renseigne l'email du client, et il ne doit pas pointer sur le bon champ

**Comment by Cerdic** [comment]
et du coup aucun problème sur le plugin bank, c'est soit ta configuration, soit un problème sur le plugin formidable_paiement (soit un problème sur le plugin formidable ?)

**Comment by sebPA06** [comment]
En effet, j'allais répondre que les formulaires de paiement sont à priori matchés via le plugin formidable_paiement. 

Et du coup avec ces éclaircissements, je vais essayer d'identifier comment le plugin fonctionne pour voir si le problème ne vient pas de la configuration. 

Je vous fais un retour dès que j'ai plus d'informations.

**Comment by Cerdic** [comment]
Je ferme ici de toute façon, si besoin voir dans le tracker de formidable_paiement
