### ISSUE TITLE
Améliorer le bouton de paiement par Stripe

### ISSUE THREAD

**Issue by Cerdic** [nursit/bank#86]
Actuellement, pour afficher le bouton de paiement, on créé déjà la demande de paiement chez Stripe. Du coup si d'autres moyens de paiement sont proposés, à chaque fois qu'un utilisateur choisit un autre moyen de paiement, ça fait une demande de paiement qui est annulée chez Stripe au bout de 24h

C'est pas très grave mais ça fait du bruit pour rien.
Il faudrait donc que le bouton commence par une requete ajax sur le site pour générer la demande de paiement chez Stripe, puis lance le paiement chez Stripe avec le checkout id qu'il a eu en retour

Ça demande un peu plus de JS et d'ajax, donc potentiellement un peu moins robuste...

**Comment by rastapopougros** [comment]
Sans JS obligatoire, ça pourrait pas faire ça par une action SPIP intermédiaire ? Le bouton appelant l'action, qui génère la demande de paiement de serveur à serveur, puis redirige vers Stripe quand reçu l'id ?

**Comment by Cerdic** [comment]
Ah j'ai fait manuellement une impémentation de ce type sur un site client dans un CVT
- le bouton payer poste simplement le formulaire en ajax
- dans le traiter on crée le checkout et on renvoie le js du checkout stripe avec un peu de code pour le lancer et un message "redirection vers..."

et ça marchait bien

Avec un bouton action c'est peut-être possible aussi, mais du coup il faut envoyer un js mini tout en vanilla dans une page html mini pour faire la redirection. A tester

**Comment by Cerdic** [comment]
c'est donc en test avant intégration
