### ISSUE TITLE
Supprimer les boutons bancontact et ideal de Stripe lorsque fait un paiement de type sabonnement

### ISSUE THREAD

**Issue by yohooololo** [nursit/bank#92]
Le bouton de paiement de Stripe génère une erreur lorsque l'on active les solutions Bancontact et Ideal et que l'on est en mode subscription.

Je m'en suis sorti en ajoutant ici : https://github.com/nursit/bank/blob/659165c9d5b383fd530c3e8697a56eb004c4ca34/presta/stripe/call/request.php#L290
`$payment_types = array_diff( $payment_types, array("bancontact","ideal"));`

**Comment by Cerdic** [comment]
corrigé dans la v5.0.15 (en principe), merci !
