### ISSUE TITLE
Problème avec Mercanet 2 (solution de la BNP)

### ISSUE THREAD

**Issue by elm31rugby** [nursit/bank#94]
Bonjour, je suis en train de configurer Bank pour Mercanet 2, la solution de la BNP. 

- J'ai bien choisi SIPS v2, service Mercanet (BNP)

- J'ai renseigné la boutique de test donnée par la BNP : 

Merchant ID (Test) : 002001000000003
Version de la clé (test) : 1
Clé secrète (Test) : 002001000000003_KEY1

Lorsque je tente le paiement, je reçois le retour suivant : 

**Invalid keyword  : code=12 message=Missing merchant transaction id key** 

J'ai posé la question à l'assistance de Mercanet, et voici leur réponse : 

`Votre boutique a fait l’objet d’une migration simplifiée/standard mercanet V2

La construction de votre solution Mercanet V2 standard/simplifiée repose sur la technologie avec les connecteurs webservices de Mercanet V2, en POST, JSON, SOAP ou SDK INAPP

Ainsi c’est le champ transactionReference qui met votre requête en anomalie.

Vous devez conserver le fonctionnement avec le principe du transaction_id (utilisation du champ s10TransactionReference.s10TransactionId).

Vos transactions doivent être uniques sur une même journée et générées en 6 chiffres.

Afin de préserver l'unicité de la transaction, le champ s10TransactionId doit être couplé avec le champ s10TransactionIdDate (à noter que celui-ci est directement alimenté par le serveur donc pas besoin de renseigner la date). Ce couple nous permet de créer le s10TransactionReference.

Ainsi, le couple s10TransactionId/s10TransactionIdDate permet d'éviter les doublons de transactions.

Pour vos transactions, vous devez donc impérativement utiliser le champ s10transactionId encodé comme suit :

// $s10TransactionReference=array(

// "s10TransactionId" => "000001",

// // "s10TransactionIdDate" => "not needed",  Le serveur Mercanet va enrichir cette information automatiquement

// );

//

Votre champ data contiendra donc une valeur correspondant à s10TransactionReference.s10TransactionId=000001 suivant l’exemple ci-dessus.

Le s10TransactionReference vous sera retourné dans la réponse du serveur Mercanet.

 `
J'avoue que ce n'est pas très clair pour moi, et je ne sais pas quoi faire... 
Bonne journée,
Éric LM

**Comment by Cerdic** [comment]
Bonjour,
je dois dire que le sipsv2 a été implémenté à la demande d'un client, et que je ne sais pas si il a été mis en production (ça marchait en test à l'époque). Je ne connais pas de site qui l'utilise en production, et donc il est possible qu'il y ait eu des évolutions d'API.

De ce que je vois ici https://documentation.sips.worldline.com/fr/WLSIPS.317-UG-Sips-Paypage-POST.html#Etape-3-Tester-sur-l-environnement-de-simulation_
selon la configuration de boutique de test ce ne sont pas les même champs qui sont attendus. 
Le plugin bank génère un `transactionReference` sur 6 caractères mais n'envoie pas de `transactionId`, je vous conseille donc de tester avec l'une des autres boutiques de test pour voir si cela fonctionne mieux.

Sinon, il faudrait reprendre et tester le module sipsv2 pour le faire coller à l'état actuel de sipsv2, mais pour être honnête je déconseille systématiquement l'utilisation de sips, y compris en v2, au profit d'autres prestataires indépendants (pas fournis par la banque) qui ont des api plus modernes et un support technique bien plus reactif

**Comment by elm31rugby** [comment]
Bonjour et merci. J'avais déjà testé la première boutique : 

ID du commerçant (merchantId) | 002001000000001
Clé secrète (secretKey) | 002001000000001_KEY1
Version de la clé (keyVersion) | 1

Avec cette boutique, j'arrive bien à la page de paiement, mais à chaque fois ma carte bleue de test est refusée, avec le message "Numero invalide".

Et donc, si j'ai bien compris, c'est foutu ? Il faut que j'encourage mon client à passer sous Stripe ? 
Bonne journée !

**Comment by elm31rugby** [comment]
Bonjour, grâce à un message trouvé sur Spip Contrib, (un utilisateur qui avait rencontré le même problème) j'ai pu faire fonctionner le plugin avec Mercanet 2. 
Le point fondamental est de demander à la BNP une version COMPLETE de Mercanet 2, et non une version simplifiée. La version simplifiée n'est pas compatible avec le plugin, tandis que la version complète l'est. 
https://contrib.spip.net/Module-de-Paiement-SIPS 
L'un des soucis est que le module de paiement ne fonctionne pas avec les boutiques de tests de la BNP. 
Donc, comme le dit @Cerdic et d'autres messages échangés sur le forum Spip le mieux est de travailler avec une autre banque en ligne. Mais si le client veut absoluement rester à la BNP... 
Bonne journée !
