### ISSUE TITLE
bank_affiche_montant

### ISSUE THREAD

**Issue by zzzazzz** [nursit/bank#97]
Salut,

En SPIP 3.2.16 ou 4.0.8 (pas testé en 4.1) le `$result` de la fonction `bank_affiche_montant()` est intercepté par (je suppose) `echapper_html_suspect()` 
![image](https://user-images.githubusercontent.com/4640081/192808933-77e5eb7a-0930-477b-ab6c-8dbc20867ac9.png)
Ce n'était pas le cas auparavant. Et ne trouve pas comment changer cela.
Cela intervient dans un squelette avec cette balise-ci :
```
#SET{prix,#PRIX*}
#SET{prix_ht,#PRIX_HT*}

#FORMULAIRE_PAYER_ACTE{
	#GET{prix},
	#ARRAY{
		montant_ht,#GET{prix_ht},
		id_commande,#ID_COMMANDE,
		id_auteur,#ID_AUTEUR
	}
}
```

**Comment by rastapopougros** [comment]
@zzzazzz il s'agit de ce problème : https://git.spip.net/spip/spip/issues/4706
Qui a été en théorie corrigé en SPIP 4.2 avec le changement de la lib de safehtml pour un truc plus moderne. Mais du coup pour SPIP 4.0 et 4.1 je ne sais pas ce qu'il en est… (3.2 bon, on est tous censé migrer maintenant)

Là ya un fix très "brutal" et temporaire pour virer tout le markup, mais qui se fait en 2s en 2 lignes : https://git.spip.net/spip-contrib-extensions/intl/issues/6#issuecomment-34494

**Comment by zzzazzz** [comment]
Yes ! C'est ce que je viens de faire, merci @rastapopougros
